name: Export Visible
#Ultimate goal is to have this run when called by export.yml
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET: ${{ secrets.SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      ZAP_DOMAIN: ${{ secrets.ZAP_DOMAIN }}
      ZAP_ENGINE: ${{ secrets.ZAP_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    strategy:
      fail-fast: false
      matrix:
        entity:
          - dcp_projects
          - dcp_projectbbls
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          
      - name: Install Dependencies
        run: python3 -m pip install .        
      
      #When this gets refactored to be reused this will already have been done
      - name: Get ${{ matrix.entity }}
        run: python3 -m src.runner ${{ matrix.entity }}

      - name: Set up mc
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
      
      - name: Send visible projects/bbls to EDM-publishing space 
        env: 
          VERSION: ${{ steps.version.outputs.version }}
        run: ./zap.sh upload_do ${{ matrix.entity }} 