name: Daily Export

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET: ${{ secrets.SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      ZAP_DOMAIN: ${{ secrets.ZAP_DOMAIN }}
      ZAP_ENGINE: ${{ secrets.ZAP_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    strategy:
      fail-fast: false
      matrix:
        entity:
          - dcp_projects
          - dcp_projectactions
          - dcp_projectbbls
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          
      - name: Install Dependencies
        run: python3 -m pip install .        
          
      - name: Get ${{ matrix.entity }}
        run: python3 -m src.runner ${{ matrix.entity }}
          
      - name: Archive to data library - PGdump
        run: |
          echo "exporting ${{ matrix.entity }}.sql"
          docker run --rm \
            -e AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT\
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\
            -e AWS_S3_BUCKET=$AWS_S3_BUCKET\
            -v $(pwd)/templates:/templates\
            -v $(pwd)/.output:/.output\
            nycplanning/library:ubuntu-latest library archive -f /templates/${{ matrix.entity }}.yml -s -l -o pgdump --compress
          
      - name: Archive to data library - CSV
        run: |
          echo "exporting ${{ matrix.entity }}.csv"
          docker run --rm \
            -e AWS_S3_ENDPOINT=$AWS_S3_ENDPOINT\
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\
            -e AWS_S3_BUCKET=$AWS_S3_BUCKET\
            -v $(pwd)/templates:/templates\
            -v $(pwd)/.output:/.output\
            nycplanning/library:ubuntu-latest library archive -f /templates/${{ matrix.entity }}.yml -s -l -o csv --compress
