name: Regular Export

on:
  schedule:
    - cron: 0 0 * * *
  push:
    paths:
      - .github/workflows/export.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET: ${{ secrets.SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      ZAP_DOMAIN: ${{ secrets.ZAP_DOMAIN }}
      ZAP_ENGINE: ${{ secrets.ZAP_ENGINE }}
    strategy:
      matrix:
        entity:
          - dcp_projects
          - dcp_projectmilestones
          - dcp_projectdispositions
          - dcp_projectactions
          - dcp_projectbbls
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          
      - name: Install Dependencies
        run: python3 -m pip install .        
          
      - name: Get ${{ matrix.entity }}
        run: python3 -m src.runner ${{ matrix.entity }}
          
