name: Export Single Dataset

on:
  workflow_dispatch:
    inputs:
        dataset:
          description: 'Name of the dataset'
          required: true
          default: dcp_projects

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SECRET: ${{ secrets.SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      ZAP_DOMAIN: ${{ secrets.ZAP_DOMAIN }}
      ZAP_ENGINE: ${{ secrets.ZAP_ENGINE }}
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_LIBRARY_BUCKET: edm-recipes

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
